pool:
  vmImage: ubuntu-latest
variables:
- group: Semgrep_Variables

steps:
- checkout: self
  clean: true
  fetchDepth: 20
  persistCredentials: true
# Replace main with the repository default branch if different.
- script: |
    python -m pip install --upgrade pip
    pip install semgrep
    echo "Semgrep full scan"
    semgrep ci
