pool:
  name: Default # Ensure this matches your self-hosted agent pool name
  demands:
    - agent.name -equals DESKTOP-7LOV8H7

variables:
- group: Semgrep_Variables

steps:
- checkout: self
  clean: true
  fetchDepth: 20
  persistCredentials: true

- script: |
    python -m pip install --upgrade pip
    pip install semgrep
    echo "Semgrep full scan"
    semgrep ci
  displayName: Run Semgrep Scan
